export const DetailCourseActionType = {
    GET_DATA_DETAIL_COURSE : 'GET_DATA_DETAIL_COURSE',
    GET_LESSON_BY_ID : 'GET_LESSON_BY_ID',
    GET_SURVEY_STUDENT_WORKED : 'GET_SURVEY_STUDENT_WORKED',
    OPEN_CHAPTER: 'OPEN_CHAPTER',
    UPDATE_LESSON_LEARNED: 'UPDATE_LESSON_LEARNED',
    UPDATE_RATING_AVG_FOR_COURSE: 'UPDATE_RATING_AVG_FOR_COURSE',
    GET_LIST_COMMENT_COURSE: 'GET_LIST_COMMENT_COURSE'
}